### ISSUE TITLE
Change the input camera

### ISSUE THREAD

**Issue by teawithfruit** [xavierfoucrier/instacam#10]
Is it possible to change the input camera on mobile or other devices?

**Comment by xavierfoucrier** [comment]
Hi @teawithfruit!
Sorry for the late reply.

It would be a great idea to be able to change the camera (front/back) on mobile or other devices, however this feature is not integrated into the plugin for now. I will work on the possibility of taking this change into account in the near future.

Thanks for your interest in the project and don't hesitate to star/watch to be notified about code modification.

**Comment by xavierfoucrier** [comment]
Note: concret sample found at https://webrtc.github.io/samples/src/content/devices/input-output and https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia. Will be usefull for feature implementation.

**Comment by xavierfoucrier** [comment]
@teawithfruit up

**Comment by xavierfoucrier** [comment]
Hi @teawithfruit,

Sorry for the long wait, I will work on that today :wink:
