### ISSUE TITLE
Old webcam API methods are being deprecated in modern browsers

### ISSUE THREAD

**Issue by 33mhz** [xavierfoucrier/instacam#12]
Firefox 60:
```
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia
jquery.instacam.min.js:1:300
URL.createObjectURL(MediaStream) is deprecated and will be removed soon.
jquery.instacam.min.js:1:816
```
Seems to give no errors on the latest Chromium, but [navigator.getUserMedia is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia#Browser_compatibility).

**Comment by xavierfoucrier** [comment]
Hi @33mhz!

Thanks for opening the issue. Yes the API has not been updated for a while: I have planned to upgrade the plugin this year and add some new features too. If you have any suggestions, just let me know :wink:

**Comment by 33mhz** [comment]
Thanks for such a prompt response. I'll probably be playing with this soon, and I'll submit a PR if I get that far. My needs are simple, but I want to keep up with browsers.

**Comment by xavierfoucrier** [comment]
No problem mate! If it's just a matter of **browser support** more than functionality, I'll make sure to update the library quickly. PRs will be appreciated if you want to contribute! :+1:

**Comment by xavierfoucrier** [comment]
Hi @33mhz!

I have done a small fix on the `development` branch a week ago, and if you want, you can check if it works on your plateform: https://github.com/xavierfoucrier/instacam/tree/development

Give a feedback if you have time.
Thanks!

**Comment by 33mhz** [comment]
Thanks! Looks good. I'll give it a shot this week.
