### ISSUE TITLE
,

### ISSUE THREAD

**Issue by anvesh523** [xavierfoucrier/instacam#6]
Sorry, wrong place I posted .... I am trying to delete .... But don't know how ....

**Comment by xavierfoucrier** [comment]
Hi,

How did you get this error message please?
Thanks for contributing ;)

**Comment by anvesh523** [comment]
Sorry for that ...... Excuse me and If u can delete r close this issue...

**Comment by xavierfoucrier** [comment]
Ok, I will do that for you ;)
No problem!
